[tox]
envlist =
    clean
    lint
    py31{1-4}
    ; mypy
    report
skip_missing_interpreters = true

[tool:pytest]
testpaths =
    tests

[gh]
python =
    3.11 = py311
    3.12 = py312
    3.13 = py313
    3.14 = py314 #, mypy

[testenv]
runner = uv-venv-lock-runner
dependency_groups =
    test
commands =
    coverage run --append -m pytest --ignore=tests/data

[testenv:mypy]
runner = uv-venv-lock-runner
commands =
    mypy {posargs:src}

[testenv:lint]
runner = uv-venv-lock-runner
skip_install = true
commands =
    ruff check --select I  # Check import order
    ruff format --check --diff  # Check formatting

[testenv:report]
skip_install = true
commands =
    coverage report
    coverage html

[testenv:clean]
skip_install = true
commands =
    coverage erase
